### ISSUE TITLE
Showing course info on hover/click

### ISSUE THREAD

**Issue by bestchai** [eyqs/req#7]
Showing only course numbers is concise, but only if you are fluent in them. It would be great if you reveal the title (description?) of the course on hover/click.

**Comment by bestchai** [comment]
Actually I just saw the course description show up as a tool tip. But, I'm not sure how I made it show up. I think the delay is set to too long. Perhaps the tooltip is not the best approach; looks long and it easily goes away on mouse move.

**Comment by eyqs** [comment]
The tooltip shows up when you press shift. What do you think about a sidebar instead?

**Comment by bestchai** [comment]
+1 for sidebar

**Comment by eyqs** [comment]
Here's a topbar instead. I'll make it work on later somewhat later (in two weeks).

**Comment by eyqs** [comment]
Here's a topbar instead. I'll make it work on mobile somewhat later (in two weeks).
