### ISSUE TITLE
Improve the flickering

### ISSUE THREAD

**Issue by bestchai** [eyqs/req#8]
Moving mouse over the course numbers produces an annoying flickering effect. This is because (1) mouse over white space removes grey background, (2) there is whitespace between every course code box.

Suggestion: have the background change be a timer that *gradually* turns background back to white after e.g., 2-3 seconds of mouse on top of white space.

**Comment by eyqs** [comment]
I did this by fading the grey background both in and out, but on second thought, maybe it only needs to be faded out...
