### ISSUE TITLE
deploy on github.io / pages

### ISSUE THREAD

**Issue by bestchai** [eyqs/req#9]
I'm not sure if this is possible, but it would be great if you had a latest version deployed on github.io so that folks don't need to clone/run a local web-server to try it out.

(e.g., I'd rather bookmark and come back to the github.io deployment than find the local cloned repo, pull, figure out what to run again, etc).

**Comment by eyqs** [comment]
Check out https://eyqs.ca/tools/req. It's deployed on the web branch atm, but I'll make sure to update all this soon (tomorrow).

**Comment by bestchai** [comment]
Neat, thanks for the link. Do you mind adding it to the README for the proj. so that it's easy to find?  (I realize it's a UBC-specific deployment, but it would act as a nice demo of the project, too)

**Comment by eyqs** [comment]
Sure thing.

**Comment by eyqs** [comment]
Everything's added now. Please let me know if you'd like to see any other features; I'll start scraping some SFU courses in the next month. Thanks for all your suggestions!
